### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/potato-ORM#6]
Read Laravel's source code to have an idea about testing all your ORM methods [here](https://github.com/laravel/framework/blob/076a054b6c78888acb3d0b93030402dbf736d824/tests/Database/DatabaseEloquentModelTest.php)

**Comment by unicodeveloper** [comment]
Why haven't you still taken care of all your tests?..I won't even try grading your third checkpoint if you don't resolve this ASAP!...Right now the tests are almost non-existent

**Comment by kola-er** [comment]
Done
